name: UltimateModerationPlus
main: me.xaxis.ultimatemoderationplus.UltimateModerationPlus
version: 1
api-version: '26.2'
commands:
  note:
    description: Manage player notes.
    usage: /<command> <add|delete|list> [player] [note]
    permission: ultimatemoderationplus.admin.note-command
  warn:
    description: Warn a player.
    usage: /<command> <add|delete|list> [player] [reason]
    permission: ultimatemoderationplus.admin.warn-command
  mute:
    description: Mute a player.
    usage: /<command> <player> <reason>
    permission: ultimatemoderationplus.admin.mute-command
  unmute:
    description: Unmute a player.
    usage: /<command> <player>
    permission: ultimatemoderationplus.admin.unmute-command
  kick:
    description: Kick a player.
    usage: /<command> <player> <reason>
    permission: ultimatemoderationplus.admin.kick-command
  freeze:
    description: Freeze a player.
    usage: /<command> <player>
    permission: ultimatemoderationplus.admin.freeze-command
  unfreeze:
    description: Unfreeze a player.
    usage: /<command> <player>
    permission: ultimatemoderationplus.admin.unfreeze-command
  ban:
    description: Ban a player.
    usage: /<command> <player> <reason>
    permission: ultimatemoderationplus.admin.ban-command
  unban:
    description: Unban a player.
    usage: /<command> <player>
    permission: ultimatemoderationplus.admin.unban-command
  tempmute:
    description: Temporarily mute a player.
    usage: /<command> <player> <duration> <reason>
    permission: ultimatemoderationplus.admin.tempmute-command
  tempban:
    description: Temporarily ban a player.
    usage: /<command> <player> <duration> <reason>
    permission: ultimatemoderationplus.admin.tempban-command
